### ISSUE TITLE
Code refactoring world model

### ISSUE THREAD

**Issue by chorhatarahuduketuri** [chorhatarahuduketuri/gc#18]
How should we refactor the world model? 
At the least, we should move things like sectors and ships out of logic/ and into model/. 

How should we store ships? With references to positions in the galaxy? Or should we just have a grid of sectors that contain systems & ships and just have space at the top of a hierarchical model?

**Comment by adrianlshaw** [comment]
Sectors and Ships are already in the model package.

A grid as the root structure seems better. When the player presses End Turn, each sector will likely need some form of processing or update. Whereas, when the screen needs to be redrawn, then only the visible sectors on the screen will be directly accessed. This is much more efficient than scanning each list for objects that only _might_  be visible on the screen in order to render them.
A grid as the root structure seems better. When the player presses End Turn, each sector will likely need some form of processing or update. Whereas, when the screen needs to be redrawn, then only the visible sectors on the screen will be directly accessed. This is so much better than scanning each list for objects that _may_  be visible on the screen in order to render them.

**Comment by chorhatarahuduketuri** [comment]
Agreed and implemented. 

Further restructuring can come under later and more specific issues.
